name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
    - name: Retrieve dependencies
      run: npm install
    - name: ESLint analysis
      run: npm run lint
    - name: TS project build
      run: npm run build
      
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker-practice/actions-setup-docker@1.0.4
      - name: Build Docker image
        run: docker build .
